version: '3.8'

services:
  rest-server:
    image: myapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - postgres  # Ensure the rest-server waits for PostgreSQL to be ready
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=swkom_dms;Username=enes;Password=sene

  web-ui:
    image: nginx-frontend
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - rest-server

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: enes
      POSTGRES_PASSWORD: sene
      POSTGRES_DB: swkom_dms
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "1919:5432"

volumes:
  postgres_data:
