version: '3.8'

services:
  rest-server:
    image: myapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - postgres
      - rabbitmq
      - elasticsearch
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=swkom_dms;Username=enes;Password=sene
      - Elasticsearch__Uri=http://elasticsearch:9200
    volumes:
      - ./SharedDirectory:/app/SharedDirectory

  web-ui:
    image: nginx-frontend
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - rest-server

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: enes
      POSTGRES_PASSWORD: sene
      POSTGRES_DB: swkom_dms
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "1919:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    depends_on:
      - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    depends_on:
      - postgres

  ocr-worker:
    build:
      context: ../OCRWorker
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - elasticsearch
    environment:
      - TESSDATA_PREFIX=/app/tessdata
      - ElasticsearchConfig__Uri=http://elasticsearch:9200
    volumes:
      - ./OCRWorker/tessdata:/app/tessdata
      - ./SharedDirectory:/app/SharedDirectory
    restart: always

volumes:
  postgres_data:
  elastic_data:
