version: '3.8'

services:
  rest-server:
    image: myapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"

  web-ui:
    image: nginx-frontend
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - rest-server
